/**
 * Auto-generated preferences configuration
 * Generated at: 2026-05-11T14:32:00.699Z
 *
 * This file is automatically generated from classification.json
 * To update this file, modify classification.json and run:
 * node v2-refactor-temp/tools/data-classify/scripts/generate-preferences.js
 *
 * ## Key Naming Convention
 *
 * All preference keys MUST follow the format: `namespace.sub.key_name`
 *
 * Rules:
 * - At least 2 segments separated by dots (.)
 * - Each segment uses lowercase letters, numbers, and underscores only
 * - Pattern: /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/
 *
 * Examples:
 * - 'app.user.avatar' (valid)
 * - 'chat.multi_select_mode' (valid)
 * - 'userAvatar' (invalid - missing dot separator)
 * - 'App.user' (invalid - uppercase not allowed)
 *
 * This convention is enforced by ESLint rule: data-schema-key/valid-key
 *
 * === AUTO-GENERATED CONTENT START ===
 */

import { TRANSLATE_PROMPT } from '@shared/config/prompts'
import * as PreferenceTypes from '@shared/data/preference/preferenceTypes'

/* eslint @typescript-eslint/member-ordering: ["error", {
  "interfaces": { "order": "alphabetically" },
  "typeLiterals": { "order": "alphabetically" }
}] */

export interface PreferenceSchemas {
  default: {
    // redux/settings/enableDeveloperMode
    'app.developer_mode.enabled': boolean
    // redux/settings/autoCheckUpdate
    'app.dist.auto_update.enabled': boolean
    // redux/settings/testChannel
    'app.dist.test_plan.channel': PreferenceTypes.UpgradeChannel
    // redux/settings/testPlan
    'app.dist.test_plan.enabled': boolean
    // redux/settings/language
    'app.language': PreferenceTypes.LanguageVarious | null
    // redux/settings/launchOnBoot
    'app.launch_on_boot': boolean
    // redux/settings/notification.assistant
    'app.notification.assistant.enabled': boolean
    // redux/settings/notification.backup
    'app.notification.backup.enabled': boolean
    // redux/settings/notification.knowledge
    'app.notification.knowledge.enabled': boolean
    // redux/settings/enableDataCollection
    'app.privacy.data_collection.enabled': boolean
    // redux/settings/proxyBypassRules
    'app.proxy.bypass_rules': string
    // redux/settings/proxyMode
    'app.proxy.mode': PreferenceTypes.ProxyMode
    // redux/settings/proxyUrl
    'app.proxy.url': string
    // redux/settings/enableSpellCheck
    'app.spell_check.enabled': boolean
    // redux/settings/spellCheckLanguages
    'app.spell_check.languages': string[]
    // redux/settings/tray
    'app.tray.enabled': boolean
    // redux/settings/trayOnClose
    'app.tray.on_close': boolean
    // redux/settings/launchToTray
    'app.tray.on_launch': boolean
    // redux/settings/useSystemTitleBar
    'app.use_system_title_bar': boolean
    // redux/settings/userId
    'app.user.id': string
    // redux/settings/userName
    'app.user.name': string
    // electronStore/ZoomFactor/ZoomFactor
    'app.zoom_factor': number
    // redux/settings/clickAssistantToShowTopic
    'assistant.click_to_show_topic': boolean
    // redux/settings/assistantIconType
    'assistant.icon_type': PreferenceTypes.AssistantIconType
    // redux/settings/showAssistants
    'assistant.tab.show': boolean
    // redux/settings/assistantsTabSortType
    'assistant.tab.sort_type': PreferenceTypes.AssistantTabSortType
    // redux/settings/codeCollapsible
    'chat.code.collapsible': boolean
    // redux/settings/codeEditor.autocompletion
    'chat.code.editor.autocompletion': boolean
    // redux/settings/codeEditor.enabled
    'chat.code.editor.enabled': boolean
    // redux/settings/codeEditor.foldGutter
    'chat.code.editor.fold_gutter': boolean
    // redux/settings/codeEditor.highlightActiveLine
    'chat.code.editor.highlight_active_line': boolean
    // redux/settings/codeEditor.keymap
    'chat.code.editor.keymap': boolean
    // redux/settings/codeEditor.themeDark
    'chat.code.editor.theme_dark': string
    // redux/settings/codeEditor.themeLight
    'chat.code.editor.theme_light': string
    // redux/settings/codeExecution.enabled
    'chat.code.execution.enabled': boolean
    // redux/settings/codeExecution.timeoutMinutes
    'chat.code.execution.timeout_minutes': number
    // redux/settings/codeFancyBlock
    'chat.code.fancy_block': boolean
    // redux/settings/codeImageTools
    'chat.code.image_tools': boolean
    // redux/settings/codePreview.themeDark
    'chat.code.preview.theme_dark': string
    // redux/settings/codePreview.themeLight
    'chat.code.preview.theme_light': string
    // redux/settings/codeShowLineNumbers
    'chat.code.show_line_numbers': boolean
    // redux/settings/codeViewer.themeDark
    'chat.code.viewer.theme_dark': string
    // redux/settings/codeViewer.themeLight
    'chat.code.viewer.theme_light': string
    // redux/settings/codeWrappable
    'chat.code.wrappable': boolean
    // target-key-definitions/complex/complex
    'chat.default_model_id': string | null
    // redux/settings/pasteLongTextAsFile
    'chat.input.paste_long_text_as_file': boolean
    // redux/settings/pasteLongTextThreshold
    'chat.input.paste_long_text_threshold': number
    // redux/settings/enableQuickPanelTriggers
    'chat.input.quick_panel.triggers_enabled': boolean
    // redux/settings/sendMessageShortcut
    'chat.input.send_message_shortcut': PreferenceTypes.SendMessageShortcut
    // redux/settings/showInputEstimatedTokens
    'chat.input.show_estimated_tokens': boolean
    // redux/settings/autoTranslateWithSpace
    'chat.input.translate.auto_translate_with_space': boolean
    // redux/settings/showTranslateConfirm
    'chat.input.translate.show_confirm': boolean
    // redux/settings/targetLanguage
    'chat.input.translate.target_language': PreferenceTypes.TranslateLangCode
    // redux/settings/confirmDeleteMessage
    'chat.message.confirm_delete': boolean
    // redux/settings/confirmRegenerateMessage
    'chat.message.confirm_regenerate': boolean
    // redux/settings/messageFont
    'chat.message.font': string
    // redux/settings/fontSize
    'chat.message.font_size': number
    // redux/settings/mathEngine
    'chat.message.math.engine': PreferenceTypes.MathEngine
    // redux/settings/mathEnableSingleDollar
    'chat.message.math.single_dollar': boolean
    // redux/settings/foldDisplayMode
    'chat.message.multi_model.fold_display_mode': PreferenceTypes.MultiModelFoldDisplayMode
    // redux/settings/gridColumns
    'chat.message.multi_model.grid_columns': number
    // redux/settings/gridPopoverTrigger
    'chat.message.multi_model.grid_popover_trigger': PreferenceTypes.MultiModelGridPopoverTrigger
    // redux/settings/multiModelMessageStyle
    'chat.message.multi_model.style': PreferenceTypes.MultiModelMessageStyle
    // redux/settings/messageNavigation
    'chat.message.navigation_mode': PreferenceTypes.ChatMessageNavigationMode
    // redux/settings/renderInputMessageAsMarkdown
    'chat.message.render_as_markdown': boolean
    // redux/settings/showMessageDivider
    'chat.message.show_divider': boolean
    // redux/settings/showMessageOutline
    'chat.message.show_outline': boolean
    // redux/settings/showPrompt
    'chat.message.show_prompt': boolean
    // redux/settings/messageStyle
    'chat.message.style': PreferenceTypes.ChatMessageStyle
    // redux/settings/thoughtAutoCollapse
    'chat.message.thought.auto_collapse': boolean
    // redux/settings/narrowMode
    'chat.narrow_mode': boolean
    // target-key-definitions/complex/complex
    'chat.web_search.compression.cutoff_limit': number
    // target-key-definitions/complex/complex
    'chat.web_search.compression.method': PreferenceTypes.WebSearchCompressionMethod
    // target-key-definitions/complex/complex
    'chat.web_search.default_fetch_urls_provider': PreferenceTypes.WebSearchProviderId | null
    // target-key-definitions/complex/complex
    'chat.web_search.default_search_keywords_provider': PreferenceTypes.WebSearchProviderId | null
    // target-key-definitions/complex/complex
    'chat.web_search.exclude_domains': string[]
    // target-key-definitions/complex/complex
    'chat.web_search.max_results': number
    // target-key-definitions/complex/complex
    'chat.web_search.provider_overrides': PreferenceTypes.WebSearchProviderOverrides
    // redux/settings/skipBackupFile
    'data.backup.general.skip_backup_file': boolean
    // redux/settings/localBackupAutoSync
    'data.backup.local.auto_sync': boolean
    // redux/settings/localBackupDir
    'data.backup.local.dir': string
    // redux/settings/localBackupMaxBackups
    'data.backup.local.max_backups': number
    // redux/settings/localBackupSkipBackupFile
    'data.backup.local.skip_backup_file': boolean
    // redux/settings/localBackupSyncInterval
    'data.backup.local.sync_interval': number
    // redux/nutstore/nutstoreAutoSync
    'data.backup.nutstore.auto_sync': boolean
    // redux/nutstore/nutstoreMaxBackups
    'data.backup.nutstore.max_backups': number
    // redux/nutstore/nutstorePath
    'data.backup.nutstore.path': string
    // redux/nutstore/nutstoreSkipBackupFile
    'data.backup.nutstore.skip_backup_file': boolean
    // redux/nutstore/nutstoreSyncInterval
    'data.backup.nutstore.sync_interval': number
    // redux/nutstore/nutstoreToken
    'data.backup.nutstore.token': string
    // redux/settings/s3.accessKeyId
    'data.backup.s3.access_key_id': string
    // redux/settings/s3.autoSync
    'data.backup.s3.auto_sync': boolean
    // redux/settings/s3.bucket
    'data.backup.s3.bucket': string
    // redux/settings/s3.endpoint
    'data.backup.s3.endpoint': string
    // redux/settings/s3.maxBackups
    'data.backup.s3.max_backups': number
    // redux/settings/s3.region
    'data.backup.s3.region': string
    // redux/settings/s3.root
    'data.backup.s3.root': string
    // redux/settings/s3.secretAccessKey
    'data.backup.s3.secret_access_key': string
    // redux/settings/s3.skipBackupFile
    'data.backup.s3.skip_backup_file': boolean
    // redux/settings/s3.syncInterval
    'data.backup.s3.sync_interval': number
    // redux/settings/webdavAutoSync
    'data.backup.webdav.auto_sync': boolean
    // redux/settings/webdavDisableStream
    'data.backup.webdav.disable_stream': boolean
    // redux/settings/webdavHost
    'data.backup.webdav.host': string
    // redux/settings/webdavMaxBackups
    'data.backup.webdav.max_backups': number
    // redux/settings/webdavPass
    'data.backup.webdav.pass': string
    // redux/settings/webdavPath
    'data.backup.webdav.path': string
    // redux/settings/webdavSkipBackupFile
    'data.backup.webdav.skip_backup_file': boolean
    // redux/settings/webdavSyncInterval
    'data.backup.webdav.sync_interval': number
    // redux/settings/webdavUser
    'data.backup.webdav.user': string
    // redux/settings/excludeCitationsInExport
    'data.export.markdown.exclude_citations': boolean
    // redux/settings/forceDollarMathInMarkdown
    'data.export.markdown.force_dollar_math': boolean
    // redux/settings/markdownExportPath
    'data.export.markdown.path': string | null
    // redux/settings/showModelNameInMarkdown
    'data.export.markdown.show_model_name': boolean
    // redux/settings/showModelProviderInMarkdown
    'data.export.markdown.show_model_provider': boolean
    // redux/settings/standardizeCitationsInExport
    'data.export.markdown.standardize_citations': boolean
    // redux/settings/useTopicNamingForMessageTitle
    'data.export.markdown.use_topic_naming_for_message_title': boolean
    // redux/settings/exportMenuOptions.docx
    'data.export.menus.docx': boolean
    // redux/settings/exportMenuOptions.image
    'data.export.menus.image': boolean
    // redux/settings/exportMenuOptions.joplin
    'data.export.menus.joplin': boolean
    // redux/settings/exportMenuOptions.markdown
    'data.export.menus.markdown': boolean
    // redux/settings/exportMenuOptions.markdown_reason
    'data.export.menus.markdown_reason': boolean
    // redux/settings/exportMenuOptions.notes
    'data.export.menus.notes': boolean
    // redux/settings/exportMenuOptions.notion
    'data.export.menus.notion': boolean
    // redux/settings/exportMenuOptions.obsidian
    'data.export.menus.obsidian': boolean
    // redux/settings/exportMenuOptions.plain_text
    'data.export.menus.plain_text': boolean
    // redux/settings/exportMenuOptions.siyuan
    'data.export.menus.siyuan': boolean
    // redux/settings/exportMenuOptions.yuque
    'data.export.menus.yuque': boolean
    // redux/settings/joplinExportReasoning
    'data.integration.joplin.export_reasoning': boolean
    // redux/settings/joplinToken
    'data.integration.joplin.token': string
    // redux/settings/joplinUrl
    'data.integration.joplin.url': string
    // redux/settings/notionApiKey
    'data.integration.notion.api_key': string
    // redux/settings/notionDatabaseID
    'data.integration.notion.database_id': string
    // redux/settings/notionExportReasoning
    'data.integration.notion.export_reasoning': boolean
    // redux/settings/notionPageNameKey
    'data.integration.notion.page_name_key': string
    // redux/settings/defaultObsidianVault
    'data.integration.obsidian.default_vault': string
    // redux/settings/siyuanApiUrl
    'data.integration.siyuan.api_url': string | null
    // redux/settings/siyuanBoxId
    'data.integration.siyuan.box_id': string | null
    // redux/settings/siyuanRootPath
    'data.integration.siyuan.root_path': string | null
    // redux/settings/siyuanToken
    'data.integration.siyuan.token': string | null
    // redux/settings/yuqueRepoId
    'data.integration.yuque.repo_id': string
    // redux/settings/yuqueToken
    'data.integration.yuque.token': string
    // redux/settings/yuqueUrl
    'data.integration.yuque.url': string
    // target-key-definitions/complex/complex
    'feature.code_cli.overrides': PreferenceTypes.CodeCliOverrides
    // redux/settings/apiServer.apiKey
    'feature.csaas.api_key': string | null
    // redux/settings/apiServer.enabled
    'feature.csaas.enabled': boolean
    // redux/settings/apiServer.host
    'feature.csaas.host': string
    // redux/settings/apiServer.port
    'feature.csaas.port': number
    // redux/preprocess/defaultProvider
    'feature.file_processing.default_document_to_markdown': PreferenceTypes.FileProcessorId | null
    // redux/ocr/imageProviderId
    'feature.file_processing.default_image_to_text': PreferenceTypes.FileProcessorId | null
    // target-key-definitions/complex/complex
    'feature.file_processing.overrides': PreferenceTypes.FileProcessorOverrides
    // redux/settings/maxKeepAliveMinapps
    'feature.mini_app.max_keep_alive': number
    // redux/settings/minappsOpenLinkExternal
    'feature.mini_app.open_link_external': boolean
    // redux/settings/minAppRegion
    'feature.mini_app.region': PreferenceTypes.MiniAppRegionFilter
    // redux/note/settings.defaultEditMode
    'feature.notes.default_edit_mode': string
    // redux/note/settings.defaultViewMode
    'feature.notes.default_view_mode': string
    // redux/note/settings.fontFamily
    'feature.notes.font_family': string
    // redux/note/settings.fontSize
    'feature.notes.font_size': number
    // redux/note/settings.isFullWidth
    'feature.notes.full_width': boolean
    // redux/note/notesPath
    'feature.notes.path': string
    // redux/note/settings.showTabStatus
    'feature.notes.show_tab_status': boolean
    // redux/note/settings.showTableOfContents
    'feature.notes.show_table_of_contents': boolean
    // redux/note/settings.showWorkspace
    'feature.notes.show_workspace': boolean
    // redux/note/sortType
    'feature.notes.sort_type': string
    // target-key-definitions/complex/complex
    'feature.openclaw.gateway_port': number
    // target-key-definitions/complex/complex
    'feature.openclaw.selected_model_id': string | null
    // redux/llm/quickAssistantId
    'feature.quick_assistant.assistant_id': string
    // redux/settings/clickTrayToShowQuickAssistant
    'feature.quick_assistant.click_tray_to_show': boolean
    // redux/settings/enableQuickAssistant
    'feature.quick_assistant.enabled': boolean
    // target-key-definitions/complex/complex
    'feature.quick_assistant.model_id': string | null
    // redux/settings/readClipboardAtStartup
    'feature.quick_assistant.read_clipboard_at_startup': boolean
    // redux/selectionStore/actionItems
    'feature.selection.action_items': PreferenceTypes.SelectionActionItem[]
    // redux/selectionStore/actionWindowOpacity
    'feature.selection.action_window_opacity': number
    // redux/selectionStore/isAutoClose
    'feature.selection.auto_close': boolean
    // redux/selectionStore/isAutoPin
    'feature.selection.auto_pin': boolean
    // redux/selectionStore/isCompact
    'feature.selection.compact': boolean
    // redux/selectionStore/selectionEnabled
    'feature.selection.enabled': boolean
    // redux/selectionStore/filterList
    'feature.selection.filter_list': string[]
    // redux/selectionStore/filterMode
    'feature.selection.filter_mode': PreferenceTypes.SelectionFilterMode
    // redux/selectionStore/isFollowToolbar
    'feature.selection.follow_toolbar': boolean
    // redux/selectionStore/isRemeberWinSize
    'feature.selection.remember_win_size': boolean
    // redux/selectionStore/triggerMode
    'feature.selection.trigger_mode': PreferenceTypes.SelectionTriggerMode
    // target-key-definitions/complex/complex
    'feature.translate.action.alter_lang': PreferenceTypes.TranslateLangCode
    // target-key-definitions/complex/complex
    'feature.translate.action.preferred_lang': PreferenceTypes.TranslateLangCode
    // dexieSettings/settings/translate:detect:method
    'feature.translate.auto_detection_method': PreferenceTypes.AutoDetectionMethod
    // target-key-definitions/complex/complex
    'feature.translate.mini_window.target_lang': PreferenceTypes.TranslateLangCode
    // target-key-definitions/complex/complex
    'feature.translate.model_id': string | null
    // redux/settings/translateModelPrompt
    'feature.translate.model_prompt': string
    // redux/translate/settings.autoCopy
    'feature.translate.page.auto_copy': boolean
    // dexieSettings/settings/translate:bidirectional:enabled
    'feature.translate.page.bidirectional_enabled': boolean
    // target-key-definitions/complex/complex
    'feature.translate.page.bidirectional_pair': PreferenceTypes.TranslateBidirectionalPair
    // dexieSettings/settings/translate:markdown:enabled
    'feature.translate.page.enable_markdown': boolean
    // dexieSettings/settings/translate:scroll:sync
    'feature.translate.page.scroll_sync': boolean
    // target-key-definitions/complex/complex
    'feature.translate.page.source_language': PreferenceTypes.TranslateSourceLanguage
    // target-key-definitions/complex/complex
    'feature.translate.page.target_language': PreferenceTypes.TranslateLangCode
    // redux/shortcuts/shortcuts.clear_topic
    'shortcut.chat.clear': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.copy_last_message
    'shortcut.chat.copy_last_message': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.edit_last_user_message
    'shortcut.chat.edit_last_user_message': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.search_message_in_chat
    'shortcut.chat.search_message': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.select_model
    'shortcut.chat.select_model': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.toggle_new_context
    'shortcut.chat.toggle_new_context': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.mini_window
    'shortcut.feature.quick_assistant.toggle_window': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.selection_assistant_select_text
    'shortcut.feature.selection.get_text': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.selection_assistant_toggle
    'shortcut.feature.selection.toggle_enabled': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.exit_fullscreen
    'shortcut.general.exit_fullscreen': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.search_message
    'shortcut.general.search': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.show_app
    'shortcut.general.show_main_window': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.show_settings
    'shortcut.general.show_settings': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.toggle_show_assistants
    'shortcut.general.toggle_sidebar': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.zoom_in
    'shortcut.general.zoom_in': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.zoom_out
    'shortcut.general.zoom_out': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.zoom_reset
    'shortcut.general.zoom_reset': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.new_topic
    'shortcut.topic.new': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.rename_topic
    'shortcut.topic.rename': PreferenceTypes.PreferenceShortcutType
    // redux/shortcuts/shortcuts.toggle_show_topics
    'shortcut.topic.toggle_show_topics': PreferenceTypes.PreferenceShortcutType
    // redux/settings/enableTopicNaming
    'topic.naming.enabled': boolean
    // target-key-definitions/complex/complex
    'topic.naming.model_id': string | null
    // redux/settings/topicNamingPrompt
    'topic.naming_prompt': string
    // redux/settings/topicPosition
    'topic.position': string
    // redux/settings/pinTopicsToTop
    'topic.tab.pin_to_top': boolean
    // redux/settings/showTopics
    'topic.tab.show': boolean
    // redux/settings/showTopicTime
    'topic.tab.show_time': boolean
    // redux/settings/customCss
    'ui.custom_css': string
    // redux/settings/navbarPosition
    'ui.navbar.position': 'left' | 'top'
    // target-key-definitions/complex/complex
    'ui.sidebar.icons.invisible': PreferenceTypes.SidebarIcon[]
    // target-key-definitions/complex/complex
    'ui.sidebar.icons.visible': PreferenceTypes.SidebarIcon[]
    // redux/settings/theme
    'ui.theme_mode': PreferenceTypes.ThemeMode
    // redux/settings/userTheme.userCodeFontFamily
    'ui.theme_user.code_font_family': string
    // redux/settings/userTheme.colorPrimary
    'ui.theme_user.color_primary': string
    // redux/settings/userTheme.userFontFamily
    'ui.theme_user.font_family': string
    // redux/settings/windowStyle
    'ui.window_style': PreferenceTypes.WindowStyle
  }
}

/* eslint sort-keys: ["error", "asc", {"caseSensitive": true, "natural": false}] */
export const DefaultPreferences: PreferenceSchemas = {
  default: {
    'app.developer_mode.enabled': false,
    'app.dist.auto_update.enabled': true,
    'app.dist.test_plan.channel': PreferenceTypes.UpgradeChannel.LATEST,
    'app.dist.test_plan.enabled': false,
    'app.language': null,
    'app.launch_on_boot': false,
    'app.notification.assistant.enabled': false,
    'app.notification.backup.enabled': false,
    'app.notification.knowledge.enabled': false,
    'app.privacy.data_collection.enabled': false,
    'app.proxy.bypass_rules': '',
    'app.proxy.mode': 'system',
    'app.proxy.url': '',
    'app.spell_check.enabled': false,
    'app.spell_check.languages': [],
    'app.tray.enabled': true,
    'app.tray.on_close': true,
    'app.tray.on_launch': false,
    'app.use_system_title_bar': false,
    'app.user.id': 'uuid()',
    'app.user.name': '',
    'app.zoom_factor': 1,
    'assistant.click_to_show_topic': true,
    'assistant.icon_type': 'emoji',
    'assistant.tab.show': true,
    'assistant.tab.sort_type': 'list',
    'chat.code.collapsible': false,
    'chat.code.editor.autocompletion': true,
    'chat.code.editor.enabled': false,
    'chat.code.editor.fold_gutter': false,
    'chat.code.editor.highlight_active_line': false,
    'chat.code.editor.keymap': false,
    'chat.code.editor.theme_dark': 'auto',
    'chat.code.editor.theme_light': 'auto',
    'chat.code.execution.enabled': false,
    'chat.code.execution.timeout_minutes': 1,
    'chat.code.fancy_block': true,
    'chat.code.image_tools': false,
    'chat.code.preview.theme_dark': 'auto',
    'chat.code.preview.theme_light': 'auto',
    'chat.code.show_line_numbers': false,
    'chat.code.viewer.theme_dark': 'auto',
    'chat.code.viewer.theme_light': 'auto',
    'chat.code.wrappable': false,
    'chat.default_model_id': null,
    'chat.input.paste_long_text_as_file': false,
    'chat.input.paste_long_text_threshold': 1500,
    'chat.input.quick_panel.triggers_enabled': false,
    'chat.input.send_message_shortcut': 'Enter',
    'chat.input.show_estimated_tokens': false,
    'chat.input.translate.auto_translate_with_space': false,
    'chat.input.translate.show_confirm': true,
    'chat.input.translate.target_language': 'en-us',
    'chat.message.confirm_delete': true,
    'chat.message.confirm_regenerate': true,
    'chat.message.font': 'system',
    'chat.message.font_size': 14,
    'chat.message.math.engine': 'KaTeX',
    'chat.message.math.single_dollar': true,
    'chat.message.multi_model.fold_display_mode': 'expanded',
    'chat.message.multi_model.grid_columns': 2,
    'chat.message.multi_model.grid_popover_trigger': 'click',
    'chat.message.multi_model.style': 'horizontal',
    'chat.message.navigation_mode': 'none',
    'chat.message.render_as_markdown': false,
    'chat.message.show_divider': true,
    'chat.message.show_outline': false,
    'chat.message.show_prompt': true,
    'chat.message.style': 'plain',
    'chat.message.thought.auto_collapse': true,
    'chat.narrow_mode': false,
    'chat.web_search.compression.cutoff_limit': 2000,
    'chat.web_search.compression.method': 'none',
    'chat.web_search.default_fetch_urls_provider': null,
    'chat.web_search.default_search_keywords_provider': null,
    'chat.web_search.exclude_domains': [],
    'chat.web_search.max_results': 5,
    'chat.web_search.provider_overrides': {},
    'data.backup.general.skip_backup_file': false,
    'data.backup.local.auto_sync': false,
    'data.backup.local.dir': '',
    'data.backup.local.max_backups': 0,
    'data.backup.local.skip_backup_file': false,
    'data.backup.local.sync_interval': 0,
    'data.backup.nutstore.auto_sync': false,
    'data.backup.nutstore.max_backups': 0,
    'data.backup.nutstore.path': '/cherry-studio',
    'data.backup.nutstore.skip_backup_file': false,
    'data.backup.nutstore.sync_interval': 0,
    'data.backup.nutstore.token': '',
    'data.backup.s3.access_key_id': '',
    'data.backup.s3.auto_sync': false,
    'data.backup.s3.bucket': '',
    'data.backup.s3.endpoint': '',
    'data.backup.s3.max_backups': 0,
    'data.backup.s3.region': '',
    'data.backup.s3.root': '',
    'data.backup.s3.secret_access_key': '',
    'data.backup.s3.skip_backup_file': false,
    'data.backup.s3.sync_interval': 0,
    'data.backup.webdav.auto_sync': false,
    'data.backup.webdav.disable_stream': false,
    'data.backup.webdav.host': '',
    'data.backup.webdav.max_backups': 0,
    'data.backup.webdav.pass': '',
    'data.backup.webdav.path': '/cherry-studio',
    'data.backup.webdav.skip_backup_file': false,
    'data.backup.webdav.sync_interval': 0,
    'data.backup.webdav.user': '',
    'data.export.markdown.exclude_citations': false,
    'data.export.markdown.force_dollar_math': false,
    'data.export.markdown.path': null,
    'data.export.markdown.show_model_name': false,
    'data.export.markdown.show_model_provider': false,
    'data.export.markdown.standardize_citations': false,
    'data.export.markdown.use_topic_naming_for_message_title': false,
    'data.export.menus.docx': true,
    'data.export.menus.image': true,
    'data.export.menus.joplin': true,
    'data.export.menus.markdown': true,
    'data.export.menus.markdown_reason': true,
    'data.export.menus.notes': true,
    'data.export.menus.notion': true,
    'data.export.menus.obsidian': true,
    'data.export.menus.plain_text': true,
    'data.export.menus.siyuan': true,
    'data.export.menus.yuque': true,
    'data.integration.joplin.export_reasoning': false,
    'data.integration.joplin.token': '',
    'data.integration.joplin.url': '',
    'data.integration.notion.api_key': '',
    'data.integration.notion.database_id': '',
    'data.integration.notion.export_reasoning': false,
    'data.integration.notion.page_name_key': 'Name',
    'data.integration.obsidian.default_vault': '',
    'data.integration.siyuan.api_url': null,
    'data.integration.siyuan.box_id': null,
    'data.integration.siyuan.root_path': null,
    'data.integration.siyuan.token': null,
    'data.integration.yuque.repo_id': '',
    'data.integration.yuque.token': '',
    'data.integration.yuque.url': '',
    'feature.code_cli.overrides': {} as PreferenceTypes.CodeCliOverrides,
    'feature.csaas.api_key': null,
    'feature.csaas.enabled': false,
    'feature.csaas.host': '127.0.0.1',
    'feature.csaas.port': 23333,
    'feature.file_processing.default_document_to_markdown': null,
    'feature.file_processing.default_image_to_text': null,
    'feature.file_processing.overrides': {} as PreferenceTypes.FileProcessorOverrides,
    'feature.mini_app.max_keep_alive': 3,
    'feature.mini_app.open_link_external': false,
    'feature.mini_app.region': 'auto',
    'feature.notes.default_edit_mode': 'preview',
    'feature.notes.default_view_mode': 'edit',
    'feature.notes.font_family': 'default',
    'feature.notes.font_size': 16,
    'feature.notes.full_width': true,
    'feature.notes.path': '',
    'feature.notes.show_tab_status': true,
    'feature.notes.show_table_of_contents': true,
    'feature.notes.show_workspace': true,
    'feature.notes.sort_type': 'sort_a2z',
    'feature.openclaw.gateway_port': 18790,
    'feature.openclaw.selected_model_id': null,
    'feature.quick_assistant.assistant_id': '',
    'feature.quick_assistant.click_tray_to_show': false,
    'feature.quick_assistant.enabled': false,
    'feature.quick_assistant.model_id': null,
    'feature.quick_assistant.read_clipboard_at_startup': true,
    'feature.selection.action_items': [
      {
        enabled: true,
        icon: 'languages',
        id: 'translate',
        isBuiltIn: true,
        name: 'selection.action.builtin.translate'
      },
      {
        enabled: true,
        icon: 'file-question',
        id: 'explain',
        isBuiltIn: true,
        name: 'selection.action.builtin.explain'
      },
      { enabled: true, icon: 'scan-text', id: 'summary', isBuiltIn: true, name: 'selection.action.builtin.summary' },
      {
        enabled: true,
        icon: 'search',
        id: 'search',
        isBuiltIn: true,
        name: 'selection.action.builtin.search',
        searchEngine: 'Google|https://www.google.com/search?q={{queryString}}'
      },
      { enabled: true, icon: 'clipboard-copy', id: 'copy', isBuiltIn: true, name: 'selection.action.builtin.copy' },
      { enabled: false, icon: 'wand-sparkles', id: 'refine', isBuiltIn: true, name: 'selection.action.builtin.refine' },
      { enabled: false, icon: 'quote', id: 'quote', isBuiltIn: true, name: 'selection.action.builtin.quote' }
    ],
    'feature.selection.action_window_opacity': 100,
    'feature.selection.auto_close': false,
    'feature.selection.auto_pin': false,
    'feature.selection.compact': false,
    'feature.selection.enabled': false,
    'feature.selection.filter_list': [],
    'feature.selection.filter_mode': PreferenceTypes.SelectionFilterMode.Default,
    'feature.selection.follow_toolbar': true,
    'feature.selection.remember_win_size': false,
    'feature.selection.trigger_mode': PreferenceTypes.SelectionTriggerMode.Selected,
    'feature.translate.action.alter_lang': 'en-us',
    'feature.translate.action.preferred_lang': 'zh-cn',
    'feature.translate.auto_detection_method': 'auto',
    'feature.translate.mini_window.target_lang': 'zh-cn',
    'feature.translate.model_id': null,
    'feature.translate.model_prompt': TRANSLATE_PROMPT,
    'feature.translate.page.auto_copy': false,
    'feature.translate.page.bidirectional_enabled': false,
    'feature.translate.page.bidirectional_pair': ['zh-cn', 'en-us'],
    'feature.translate.page.enable_markdown': true,
    'feature.translate.page.scroll_sync': false,
    'feature.translate.page.source_language': 'auto',
    'feature.translate.page.target_language': 'zh-cn',
    'shortcut.chat.clear': { binding: ['CommandOrControl', 'L'], enabled: true },
    'shortcut.chat.copy_last_message': { binding: ['CommandOrControl', 'Shift', 'C'], enabled: false },
    'shortcut.chat.edit_last_user_message': { binding: ['CommandOrControl', 'Shift', 'E'], enabled: false },
    'shortcut.chat.search_message': { binding: ['CommandOrControl', 'F'], enabled: true },
    'shortcut.chat.select_model': { binding: ['CommandOrControl', 'Shift', 'M'], enabled: true },
    'shortcut.chat.toggle_new_context': { binding: ['CommandOrControl', 'K'], enabled: true },
    'shortcut.feature.quick_assistant.toggle_window': { binding: ['CommandOrControl', 'E'], enabled: false },
    'shortcut.feature.selection.get_text': { binding: [], enabled: false },
    'shortcut.feature.selection.toggle_enabled': { binding: [], enabled: false },
    'shortcut.general.exit_fullscreen': { binding: ['Escape'], enabled: true },
    'shortcut.general.search': { binding: ['CommandOrControl', 'Shift', 'F'], enabled: true },
    'shortcut.general.show_main_window': { binding: [], enabled: false },
    'shortcut.general.show_settings': { binding: ['CommandOrControl', ','], enabled: true },
    'shortcut.general.toggle_sidebar': { binding: ['CommandOrControl', '['], enabled: true },
    'shortcut.general.zoom_in': { binding: ['CommandOrControl', '='], enabled: true },
    'shortcut.general.zoom_out': { binding: ['CommandOrControl', '-'], enabled: true },
    'shortcut.general.zoom_reset': { binding: ['CommandOrControl', '0'], enabled: true },
    'shortcut.topic.new': { binding: ['CommandOrControl', 'N'], enabled: true },
    'shortcut.topic.rename': { binding: ['CommandOrControl', 'T'], enabled: false },
    'shortcut.topic.toggle_show_topics': { binding: ['CommandOrControl', ']'], enabled: true },
    'topic.naming.enabled': true,
    'topic.naming.model_id': null,
    'topic.naming_prompt': '',
    'topic.position': 'left',
    'topic.tab.pin_to_top': false,
    'topic.tab.show': true,
    'topic.tab.show_time': false,
    'ui.custom_css': '',
    'ui.navbar.position': 'top',
    'ui.sidebar.icons.invisible': [],
    'ui.sidebar.icons.visible': [
      'assistants',
      'store',
      'paintings',
      'translate',
      'mini_app',
      'knowledge',
      'files',
      'code_tools',
      'notes'
    ],
    'ui.theme_mode': PreferenceTypes.ThemeMode.system,
    'ui.theme_user.code_font_family': '',
    'ui.theme_user.color_primary': '#00b96b',
    'ui.theme_user.font_family': '',
    'ui.window_style': 'opaque'
  }
}

// === AUTO-GENERATED CONTENT END ===

/**
 * 生成统计:
 * - 总配置项: 230
 * - electronStore项: 1
 * - redux项: 202
 * - localStorage项: 0
 * - dexieSettings项: 4
 */
