packages:
  - 'packages/*'

overrides:
  basic-ftp: '>=5.2.0'
  fast-xml-parser: '>=5.3.6'
  protobufjs: '^7.5.5'
  'minimatch@<3.1.3': '3.1.5'
  'minimatch@>=5.0.0 <5.1.7': '5.1.7'
  'minimatch@>=9.0.0 <9.0.6': '9.0.6'
  'minimatch@>=10.0.0 <10.2.1': '10.2.1'
  '@smithy/types': '4.7.1'
  '@codemirror/state': '6.5.4'
  '@codemirror/view': '6.39.16'
  '@codemirror/language': '6.12.2'
  '@codemirror/lint': '6.9.5'
  '@lezer/common': '1.5.1'
  prosemirror-model: '1.25.9'
  prosemirror-view: '1.41.9'
  prosemirror-transform: '1.12.0'
  esbuild: '^0.25.0'
  node-abi: '4.28.0'
  openai: 'npm:@cherrystudio/openai@6.15.0'
  tar-fs: '^2.1.4'
  undici: '6.23.0'
  vite: 'npm:rolldown-vite@7.3.0'
  yaml: '2.8.2'
  '@img/sharp-darwin-arm64': '0.34.5'
  '@img/sharp-darwin-x64': '0.34.5'
  '@img/sharp-linux-arm': '0.34.5'
  '@img/sharp-linux-arm64': '0.34.5'
  '@img/sharp-linux-x64': '0.34.5'
  '@img/sharp-win32-x64': '0.34.5'
  '@langchain/core': '1.0.2'
  '@napi-rs/canvas': '0.1.97'
  '@ai-sdk/provider-utils': '4.0.23'

patchedDependencies:
  '@napi-rs/system-ocr@1.0.2': patches/@napi-rs-system-ocr-npm-1.0.2-59e7a78e8b.patch
  'tesseract.js@6.0.1': patches/tesseract.js-npm-6.0.1-2562a7e46d.patch
  '@langchain/core@1.0.2': patches/@langchain-core-npm-1.0.2-183ef83fe4.patch
  '@langchain/openai@1.0.0': patches/@langchain-openai-npm-1.0.0-474d0ad9d4.patch
  'antd@5.27.0': patches/antd-npm-5.27.0-aa91c36546.patch
  'electron-updater@6.7.0': patches/electron-updater-npm-6.7.0-47b11bb0d4.patch
  'atomically@1.7.0': patches/atomically-npm-1.7.0-e742e5293b.patch
  'file-stream-rotator@0.6.1': patches/file-stream-rotator-npm-0.6.1-eab45fb13d.patch
  'ollama-ai-provider-v2@3.3.1': patches/ollama-ai-provider-v2@3.3.1.patch
  '@openrouter/ai-sdk-provider': patches/@openrouter__ai-sdk-provider.patch
  '@opeoginni/github-copilot-openai-compatible@1.0.0': patches/@opeoginni__github-copilot-openai-compatible@1.0.0.patch
  '@ai-sdk/openai-compatible@2.0.37': patches/@ai-sdk__openai-compatible@2.0.37.patch
  '@ai-sdk/openai@3.0.53': patches/@ai-sdk__openai@3.0.53.patch
  '@ai-sdk/xai@3.0.83': patches/@ai-sdk__xai@3.0.83.patch
  '@ai-sdk/google@3.0.64': patches/@ai-sdk__google@3.0.64.patch
  '@libsql/client@0.15.15': patches/@libsql__client@0.15.15.patch
  '@ai-sdk/anthropic': patches/@ai-sdk__anthropic.patch
  '@ai-sdk/deepseek@2.0.30': patches/@ai-sdk__deepseek@2.0.30.patch
  'ai@6.0.143': patches/ai@6.0.143.patch
  '@tiptap/extension-drag-handle@3.26.1': patches/@tiptap__extension-drag-handle@3.26.1.patch
  '@tiptap/markdown@3.26.1': patches/@tiptap__markdown@3.26.1.patch

allowBuilds:
  '@j178/prek': true
  '@paymoapp/electron-shutdown-handler': true
  '@scarf/scarf': true
  '@swc/core': true
  canvas: true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: true
  protobufjs: true
  registry-js: true
  selection-hook: true
  sharp: true
  tesseract.js: true
  zipfile: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current
