/**
 * Auto-generated icon catalog for runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-05-22T11:31:59.026Z
 * Total icons: 35
 */
import { type CompoundIcon } from '../types'
import { AyaIcon } from './aya'
import { ClaudeIcon } from './claude'
import { CodegeexIcon } from './codegeex'
import { DoubaoIcon } from './doubao'
import { GeminiIcon } from './gemini'
import { GemmaIcon } from './gemma'
import { GlmIcon } from './glm'
import { Gpt5Icon } from './gpt-5'
import { Gpt51Icon } from './gpt-5-1'
import { Gpt51ChatIcon } from './gpt-5-1-chat'
import { Gpt51CodexIcon } from './gpt-5-1-codex'
import { Gpt51CodexMiniIcon } from './gpt-5-1-codex-mini'
import { Gpt52Icon } from './gpt-5-2'
import { Gpt52ProIcon } from './gpt-5-2-pro'
import { Gpt5ChatIcon } from './gpt-5-chat'
import { Gpt5CodexIcon } from './gpt-5-codex'
import { Gpt5MiniIcon } from './gpt-5-mini'
import { Gpt5NanoIcon } from './gpt-5-nano'
import { GptImage1Icon } from './gpt-image-1'
import { GptImage15Icon } from './gpt-image-1-5'
import { GptOss20bIcon } from './gpt-oss-20b'
import { GptOss120bIcon } from './gpt-oss-120b'
import { GrokIcon } from './grok'
import { HailuoIcon } from './hailuo'
import { HunyuanIcon } from './hunyuan'
import { IbmIcon } from './ibm'
import { KimiIcon } from './kimi'
import { LingIcon } from './ling'
import { MimoIcon } from './mimo'
import { NovaIcon } from './nova'
import { PalmIcon } from './palm'
import { QwenIcon } from './qwen'
import { SensenovaIcon } from './sensenova'
import { SoraIcon } from './sora'
import { TrinityIcon } from './trinity'

export const MODEL_ICON_CATALOG = {
  aya: AyaIcon,
  claude: ClaudeIcon,
  codegeex: CodegeexIcon,
  doubao: DoubaoIcon,
  gemini: GeminiIcon,
  gemma: GemmaIcon,
  glm: GlmIcon,
  'gpt-5': Gpt5Icon,
  'gpt-5-1': Gpt51Icon,
  'gpt-5-1-chat': Gpt51ChatIcon,
  'gpt-5-1-codex': Gpt51CodexIcon,
  'gpt-5-1-codex-mini': Gpt51CodexMiniIcon,
  'gpt-5-2': Gpt52Icon,
  'gpt-5-2-pro': Gpt52ProIcon,
  'gpt-5-chat': Gpt5ChatIcon,
  'gpt-5-codex': Gpt5CodexIcon,
  'gpt-5-mini': Gpt5MiniIcon,
  'gpt-5-nano': Gpt5NanoIcon,
  'gpt-image-1': GptImage1Icon,
  'gpt-image-1-5': GptImage15Icon,
  'gpt-oss-120b': GptOss120bIcon,
  'gpt-oss-20b': GptOss20bIcon,
  grok: GrokIcon,
  hailuo: HailuoIcon,
  hunyuan: HunyuanIcon,
  ibm: IbmIcon,
  kimi: KimiIcon,
  ling: LingIcon,
  mimo: MimoIcon,
  nova: NovaIcon,
  palm: PalmIcon,
  qwen: QwenIcon,
  sensenova: SensenovaIcon,
  sora: SoraIcon,
  trinity: TrinityIcon
} as const satisfies Record<string, CompoundIcon>

export type ModelIconKey = keyof typeof MODEL_ICON_CATALOG
