/**
 * Auto-generated icon catalog for runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-05-15T02:44:13.620Z
 * Total icons: 35
 */
import { type CompoundIcon } from '../types'
import { AyaIcon } from './aya'
import { ClaudeIcon } from './claude'
import { CodegeexIcon } from './codegeex'
import { DoubaoIcon } from './doubao'
import { GeminiIcon } from './gemini'
import { GemmaIcon } from './gemma'
import { GlmIcon } from './glm'
import { Gpt5Icon } from './gpt5'
import { Gpt5ChatIcon } from './gpt5Chat'
import { Gpt5CodexIcon } from './gpt5Codex'
import { Gpt5MiniIcon } from './gpt5Mini'
import { Gpt5NanoIcon } from './gpt5Nano'
import { Gpt51Icon } from './gpt51'
import { Gpt51ChatIcon } from './gpt51Chat'
import { Gpt51CodexIcon } from './gpt51Codex'
import { Gpt51CodexMiniIcon } from './gpt51CodexMini'
import { Gpt52Icon } from './gpt52'
import { Gpt52ProIcon } from './gpt52Pro'
import { GptImage1Icon } from './gptImage1'
import { GptImage15Icon } from './gptImage15'
import { GptOss20bIcon } from './gptOss20b'
import { GptOss120bIcon } from './gptOss120b'
import { GrokIcon } from './grok'
import { HailuoIcon } from './hailuo'
import { HunyuanIcon } from './hunyuan'
import { IbmIcon } from './ibm'
import { KimiIcon } from './kimi'
import { LingIcon } from './ling'
import { MimoIcon } from './mimo'
import { NovaIcon } from './nova'
import { PalmIcon } from './palm'
import { QwenIcon } from './qwen'
import { SensenovaIcon } from './sensenova'
import { SoraIcon } from './sora'
import { TrinityIcon } from './trinity'

export const MODEL_ICON_CATALOG = {
  aya: AyaIcon,
  claude: ClaudeIcon,
  codegeex: CodegeexIcon,
  doubao: DoubaoIcon,
  gemini: GeminiIcon,
  gemma: GemmaIcon,
  glm: GlmIcon,
  gpt5: Gpt5Icon,
  gpt51: Gpt51Icon,
  gpt51Chat: Gpt51ChatIcon,
  gpt51Codex: Gpt51CodexIcon,
  gpt51CodexMini: Gpt51CodexMiniIcon,
  gpt52: Gpt52Icon,
  gpt52Pro: Gpt52ProIcon,
  gpt5Chat: Gpt5ChatIcon,
  gpt5Codex: Gpt5CodexIcon,
  gpt5Mini: Gpt5MiniIcon,
  gpt5Nano: Gpt5NanoIcon,
  gptImage1: GptImage1Icon,
  gptImage15: GptImage15Icon,
  gptOss120b: GptOss120bIcon,
  gptOss20b: GptOss20bIcon,
  grok: GrokIcon,
  hailuo: HailuoIcon,
  hunyuan: HunyuanIcon,
  ibm: IbmIcon,
  kimi: KimiIcon,
  ling: LingIcon,
  mimo: MimoIcon,
  nova: NovaIcon,
  palm: PalmIcon,
  qwen: QwenIcon,
  sensenova: SensenovaIcon,
  sora: SoraIcon,
  trinity: TrinityIcon
} as const satisfies Record<string, CompoundIcon>

export type ModelIconKey = keyof typeof MODEL_ICON_CATALOG
