/**
 * Auto-generated icon catalog for runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-05-15T12:20:09.104Z
 * Total icons: 159
 */
import { type CompoundIcon } from '../types'
import { MinTop3Icon } from './3minTop'
import { Ai302Icon } from './302ai'
import { AbacusIcon } from './abacus'
import { Ai21Icon } from './ai21'
import { AihubmixIcon } from './aihubmix'
import { AionlabsIcon } from './aionlabs'
import { AiOnlyIcon } from './aiOnly'
import { AiStudioIcon } from './aiStudio'
import { AlayanewIcon } from './alayanew'
import { AllenaiIcon } from './allenai'
import { AnthropicIcon } from './anthropic'
import { ApplicationIcon } from './application'
import { ArceeAiIcon } from './arceeAi'
import { AwsBedrockIcon } from './awsBedrock'
import { AzureaiIcon } from './azureai'
import { BaaiIcon } from './baai'
import { BaichuanIcon } from './baichuan'
import { BaiduIcon } from './baidu'
import { BaiduCloudIcon } from './baiduCloud'
import { BailianIcon } from './bailian'
import { BflIcon } from './bfl'
import { BingIcon } from './bing'
import { BochaIcon } from './bocha'
import { BoltNewIcon } from './boltNew'
import { BurncloudIcon } from './burncloud'
import { BytedanceIcon } from './bytedance'
import { CephalonIcon } from './cephalon'
import { CerebrasIcon } from './cerebras'
import { CherryinIcon } from './cherryin'
import { CloudflareIcon } from './cloudflare'
import { CohereIcon } from './cohere'
import { ComposioIcon } from './composio'
import { CozeIcon } from './coze'
import { DangbeiIcon } from './dangbei'
import { DashscopeIcon } from './dashscope'
import { DatabricksIcon } from './databricks'
import { DeepcogitoIcon } from './deepcogito'
import { DeepseekIcon } from './deepseek'
import { DevvIcon } from './devv'
import { DifyIcon } from './dify'
import { DmxapiIcon } from './dmxapi'
import { Doc2xIcon } from './doc2x'
import { DolaIcon } from './dola'
import { DolphinAiIcon } from './dolphinAi'
import { DoubaoIcon } from './doubao'
import { DuckIcon } from './duck'
import { ElevenlabsIcon } from './elevenlabs'
import { EssentialAiIcon } from './essentialAi'
import { ExaIcon } from './exa'
import { FeloIcon } from './felo'
import { FireworksIcon } from './fireworks'
import { FlowithIcon } from './flowith'
import { GensparkIcon } from './genspark'
import { GiteeAiIcon } from './giteeAi'
import { GithubIcon } from './github'
import { GithubCopilotIcon } from './githubCopilot'
import { GlamaIcon } from './glama'
import { GoogleIcon } from './google'
import { GpustackIcon } from './gpustack'
import { GraphRagIcon } from './graphRag'
import { GrokIcon } from './grok'
import { GroqIcon } from './groq'
import { HigressIcon } from './higress'
import { HuggingfaceIcon } from './huggingface'
import { HyperbolicIcon } from './hyperbolic'
import { IdeogramIcon } from './ideogram'
import { ImaIcon } from './ima'
import { InceptionlabsIcon } from './inceptionlabs'
import { InfiniIcon } from './infini'
import { InflectionIcon } from './inflection'
import { IntelIcon } from './intel'
import { InternlmIcon } from './internlm'
import { JimengIcon } from './jimeng'
import { JinaIcon } from './jina'
import { KlingIcon } from './kling'
import { KwaipilotIcon } from './kwaipilot'
import { LambdaIcon } from './lambda'
import { LanyunIcon } from './lanyun'
import { LeptonIcon } from './lepton'
import { LingxiIcon } from './lingxi'
import { LiquidIcon } from './liquid'
import { LmstudioIcon } from './lmstudio'
import { LongcatIcon } from './longcat'
import { MacosIcon } from './macos'
import { McpIcon } from './mcp'
import { McprouterIcon } from './mcprouter'
import { McpsoIcon } from './mcpso'
import { MetaIcon } from './meta'
import { MetasoIcon } from './metaso'
import { MineruIcon } from './mineru'
import { MinimaxIcon } from './minimax'
import { MinimaxAgentIcon } from './minimaxAgent'
import { MistralIcon } from './mistral'
import { MixedbreadIcon } from './mixedbread'
import { ModelscopeIcon } from './modelscope'
import { MonicaIcon } from './monica'
import { MoonshotIcon } from './moonshot'
import { N8nIcon } from './n8n'
import { NamiAiIcon } from './namiAi'
import { NeteaseYoudaoIcon } from './neteaseYoudao'
import { NewapiIcon } from './newapi'
import { NomicIcon } from './nomic'
import { NotebooklmIcon } from './notebooklm'
import { NousresearchIcon } from './nousresearch'
import { NvidiaIcon } from './nvidia'
import { O3Icon } from './o3'
import { OcoolaiIcon } from './ocoolai'
import { OllamaIcon } from './ollama'
import { OpenaiIcon } from './openai'
import { OpenclawIcon } from './openclaw'
import { OpenrouterIcon } from './openrouter'
import { PaddleocrIcon } from './paddleocr'
import { PerplexityIcon } from './perplexity'
import { Ph8Icon } from './ph8'
import { PoeIcon } from './poe'
import { PpioIcon } from './ppio'
import { PulseIcon } from './pulse'
import { QiniuIcon } from './qiniu'
import { QueritIcon } from './querit'
import { QwenIcon } from './qwen'
import { RecraftIcon } from './recraft'
import { RelaceIcon } from './relace'
import { RiverflowIcon } from './riverflow'
import { RunwayIcon } from './runway'
import { SearxngIcon } from './searxng'
import { SensetimeIcon } from './sensetime'
import { SiliconIcon } from './silicon'
import { SkyworkIcon } from './skywork'
import { SmitheryIcon } from './smithery'
import { SophnetIcon } from './sophnet'
import { StabilityIcon } from './stability'
import { StepIcon } from './step'
import { StreamlakeIcon } from './streamlake'
import { SunoIcon } from './suno'
import { TavilyIcon } from './tavily'
import { TencentCloudTiIcon } from './tencentCloudTi'
import { TesseractJsIcon } from './tesseractJs'
import { ThinkAnyIcon } from './thinkAny'
import { TngIcon } from './tng'
import { TogetherIcon } from './together'
import { TokenfluxIcon } from './tokenflux'
import { TwitterIcon } from './twitter'
import { UpstageIcon } from './upstage'
import { VercelIcon } from './vercel'
import { VertexaiIcon } from './vertexai'
import { ViduIcon } from './vidu'
import { VolcengineIcon } from './volcengine'
import { VoyageIcon } from './voyage'
import { WenxinIcon } from './wenxin'
import { WorkersAiIcon } from './workersAi'
import { XiaoyiIcon } from './xiaoyi'
import { XinghuoIcon } from './xinghuo'
import { XirangIcon } from './xirang'
import { YouIcon } from './you'
import { YuanbaoIcon } from './yuanbao'
import { ZAiIcon } from './zAi'
import { ZeroOneIcon } from './zeroOne'
import { ZhidaIcon } from './zhida'
import { ZhipuIcon } from './zhipu'

export const PROVIDER_ICON_CATALOG = {
  '302ai': Ai302Icon,
  '3minTop': MinTop3Icon,
  abacus: AbacusIcon,
  ai21: Ai21Icon,
  aiOnly: AiOnlyIcon,
  aiStudio: AiStudioIcon,
  aihubmix: AihubmixIcon,
  aionlabs: AionlabsIcon,
  alayanew: AlayanewIcon,
  allenai: AllenaiIcon,
  anthropic: AnthropicIcon,
  application: ApplicationIcon,
  arceeAi: ArceeAiIcon,
  awsBedrock: AwsBedrockIcon,
  azureai: AzureaiIcon,
  baai: BaaiIcon,
  baichuan: BaichuanIcon,
  baidu: BaiduIcon,
  baiduCloud: BaiduCloudIcon,
  bailian: BailianIcon,
  bfl: BflIcon,
  bing: BingIcon,
  bocha: BochaIcon,
  boltNew: BoltNewIcon,
  burncloud: BurncloudIcon,
  bytedance: BytedanceIcon,
  cephalon: CephalonIcon,
  cerebras: CerebrasIcon,
  cherryin: CherryinIcon,
  cloudflare: CloudflareIcon,
  cohere: CohereIcon,
  composio: ComposioIcon,
  coze: CozeIcon,
  dangbei: DangbeiIcon,
  dashscope: DashscopeIcon,
  databricks: DatabricksIcon,
  deepcogito: DeepcogitoIcon,
  deepseek: DeepseekIcon,
  devv: DevvIcon,
  dify: DifyIcon,
  dmxapi: DmxapiIcon,
  doc2x: Doc2xIcon,
  dola: DolaIcon,
  dolphinAi: DolphinAiIcon,
  doubao: DoubaoIcon,
  duck: DuckIcon,
  elevenlabs: ElevenlabsIcon,
  essentialAi: EssentialAiIcon,
  exa: ExaIcon,
  felo: FeloIcon,
  fireworks: FireworksIcon,
  flowith: FlowithIcon,
  genspark: GensparkIcon,
  giteeAi: GiteeAiIcon,
  github: GithubIcon,
  githubCopilot: GithubCopilotIcon,
  glama: GlamaIcon,
  google: GoogleIcon,
  gpustack: GpustackIcon,
  graphRag: GraphRagIcon,
  grok: GrokIcon,
  groq: GroqIcon,
  higress: HigressIcon,
  huggingface: HuggingfaceIcon,
  hyperbolic: HyperbolicIcon,
  ideogram: IdeogramIcon,
  ima: ImaIcon,
  inceptionlabs: InceptionlabsIcon,
  infini: InfiniIcon,
  inflection: InflectionIcon,
  intel: IntelIcon,
  internlm: InternlmIcon,
  jimeng: JimengIcon,
  jina: JinaIcon,
  kling: KlingIcon,
  kwaipilot: KwaipilotIcon,
  lambda: LambdaIcon,
  lanyun: LanyunIcon,
  lepton: LeptonIcon,
  lingxi: LingxiIcon,
  liquid: LiquidIcon,
  lmstudio: LmstudioIcon,
  longcat: LongcatIcon,
  macos: MacosIcon,
  mcp: McpIcon,
  mcprouter: McprouterIcon,
  mcpso: McpsoIcon,
  meta: MetaIcon,
  metaso: MetasoIcon,
  mineru: MineruIcon,
  minimax: MinimaxIcon,
  minimaxAgent: MinimaxAgentIcon,
  mistral: MistralIcon,
  mixedbread: MixedbreadIcon,
  modelscope: ModelscopeIcon,
  monica: MonicaIcon,
  moonshot: MoonshotIcon,
  n8n: N8nIcon,
  namiAi: NamiAiIcon,
  neteaseYoudao: NeteaseYoudaoIcon,
  newapi: NewapiIcon,
  nomic: NomicIcon,
  notebooklm: NotebooklmIcon,
  nousresearch: NousresearchIcon,
  nvidia: NvidiaIcon,
  o3: O3Icon,
  ocoolai: OcoolaiIcon,
  ollama: OllamaIcon,
  openai: OpenaiIcon,
  openclaw: OpenclawIcon,
  openrouter: OpenrouterIcon,
  paddleocr: PaddleocrIcon,
  perplexity: PerplexityIcon,
  ph8: Ph8Icon,
  poe: PoeIcon,
  ppio: PpioIcon,
  pulse: PulseIcon,
  qiniu: QiniuIcon,
  querit: QueritIcon,
  qwen: QwenIcon,
  recraft: RecraftIcon,
  relace: RelaceIcon,
  riverflow: RiverflowIcon,
  runway: RunwayIcon,
  searxng: SearxngIcon,
  sensetime: SensetimeIcon,
  silicon: SiliconIcon,
  skywork: SkyworkIcon,
  smithery: SmitheryIcon,
  sophnet: SophnetIcon,
  stability: StabilityIcon,
  step: StepIcon,
  streamlake: StreamlakeIcon,
  suno: SunoIcon,
  tavily: TavilyIcon,
  tencentCloudTi: TencentCloudTiIcon,
  tesseractJs: TesseractJsIcon,
  thinkAny: ThinkAnyIcon,
  tng: TngIcon,
  together: TogetherIcon,
  tokenflux: TokenfluxIcon,
  twitter: TwitterIcon,
  upstage: UpstageIcon,
  vercel: VercelIcon,
  vertexai: VertexaiIcon,
  vidu: ViduIcon,
  volcengine: VolcengineIcon,
  voyage: VoyageIcon,
  wenxin: WenxinIcon,
  workersAi: WorkersAiIcon,
  xiaoyi: XiaoyiIcon,
  xinghuo: XinghuoIcon,
  xirang: XirangIcon,
  you: YouIcon,
  yuanbao: YuanbaoIcon,
  zAi: ZAiIcon,
  zeroOne: ZeroOneIcon,
  zhida: ZhidaIcon,
  zhipu: ZhipuIcon
} as const satisfies Record<string, CompoundIcon>

export type ProviderIconKey = keyof typeof PROVIDER_ICON_CATALOG
