export { AdapterTracer } from './adapters/aiSdk/adapterTracer'
export { AiSdkSpanAdapter } from './adapters/aiSdk/aiSdkSpanAdapter'
export type { ClaudeCodeTraceContext } from './adapters/claudeCode/ClaudeCodeOtlpAdapter'
export { ClaudeCodeOtlpAdapter } from './adapters/claudeCode/ClaudeCodeOtlpAdapter'
export { TRACER_NAME } from './constants'
export type { AiTurnTraceHandle, AiTurnTraceMeta } from './core/AiTurnTrace'
export { deriveRootSpanId, startAiChildTurnSpan, startAiTurnTrace } from './core/AiTurnTrace'
export { createHttpTraceFetch, type HttpTraceOptions } from './httpTraceFetch'
export type { ObservabilitySink } from './sinks/ObservabilitySink'
export { observabilitySinks } from './sinks/ObservabilitySinkRegistry'
export { applyTurnInputAttributes, applyTurnOutputAttributes, type TurnInputInfo } from './turnSpanAttributes'
