/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppRouteImport } from './routes/app'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsWebsearchRouteImport } from './routes/settings/websearch'
import { Route as SettingsShortcutRouteImport } from './routes/settings/shortcut'
import { Route as SettingsSelectionAssistantRouteImport } from './routes/settings/selection-assistant'
import { Route as SettingsScheduledTasksRouteImport } from './routes/settings/scheduled-tasks'
import { Route as SettingsQuickAssistantRouteImport } from './routes/settings/quick-assistant'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider'
import { Route as SettingsPluginsRouteImport } from './routes/settings/plugins'
import { Route as SettingsModelRouteImport } from './routes/settings/model'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsFileProcessingRouteImport } from './routes/settings/file-processing'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsChannelsRouteImport } from './routes/settings/channels'
import { Route as SettingsApiGatewayRouteImport } from './routes/settings/api-gateway'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as AppTranslateRouteImport } from './routes/app/translate'
import { Route as AppOpenclawRouteImport } from './routes/app/openclaw'
import { Route as AppNotesRouteImport } from './routes/app/notes'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as AppLaunchpadRouteImport } from './routes/app/launchpad'
import { Route as AppKnowledgeRouteImport } from './routes/app/knowledge'
import { Route as AppFilesRouteImport } from './routes/app/files'
import { Route as AppCodeRouteImport } from './routes/app/code'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAgentsRouteImport } from './routes/app/agents'
import { Route as SettingsMcpIndexRouteImport } from './routes/settings/mcp/index'
import { Route as AppPaintingsIndexRouteImport } from './routes/app/paintings/index'
import { Route as AppMiniAppIndexRouteImport } from './routes/app/mini-app/index'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp/servers'
import { Route as SettingsMcpNpxSearchRouteImport } from './routes/settings/mcp/npx-search'
import { Route as SettingsMcpMcpInstallRouteImport } from './routes/settings/mcp/mcp-install'
import { Route as SettingsMcpMarketplacesRouteImport } from './routes/settings/mcp/marketplaces'
import { Route as SettingsMcpBuiltinRouteImport } from './routes/settings/mcp/builtin'
import { Route as SettingsMcpSplatRouteImport } from './routes/settings/mcp/$'
import { Route as AppPaintingsSplatRouteImport } from './routes/app/paintings/$'
import { Route as AppMiniAppAppIdRouteImport } from './routes/app/mini-app/$appId'
import { Route as SettingsMcpSettingsServerIdRouteImport } from './routes/settings/mcp/settings.$serverId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWebsearchRoute = SettingsWebsearchRouteImport.update({
  id: '/websearch',
  path: '/websearch',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShortcutRoute = SettingsShortcutRouteImport.update({
  id: '/shortcut',
  path: '/shortcut',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSelectionAssistantRoute =
  SettingsSelectionAssistantRouteImport.update({
    id: '/selection-assistant',
    path: '/selection-assistant',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsScheduledTasksRoute = SettingsScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsQuickAssistantRoute = SettingsQuickAssistantRouteImport.update({
  id: '/quick-assistant',
  path: '/quick-assistant',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProviderRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelRoute = SettingsModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFileProcessingRoute = SettingsFileProcessingRouteImport.update({
  id: '/file-processing',
  path: '/file-processing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChannelsRoute = SettingsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiGatewayRoute = SettingsApiGatewayRouteImport.update({
  id: '/api-gateway',
  path: '/api-gateway',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const AppTranslateRoute = AppTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AppRoute,
} as any)
const AppOpenclawRoute = AppOpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppLaunchpadRoute = AppLaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const SettingsMcpIndexRoute = SettingsMcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const AppPaintingsIndexRoute = AppPaintingsIndexRouteImport.update({
  id: '/paintings/',
  path: '/paintings/',
  getParentRoute: () => AppRoute,
} as any)
const AppMiniAppIndexRoute = AppMiniAppIndexRouteImport.update({
  id: '/mini-app/',
  path: '/mini-app/',
  getParentRoute: () => AppRoute,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpNpxSearchRoute = SettingsMcpNpxSearchRouteImport.update({
  id: '/npx-search',
  path: '/npx-search',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMcpInstallRoute = SettingsMcpMcpInstallRouteImport.update({
  id: '/mcp-install',
  path: '/mcp-install',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMarketplacesRoute = SettingsMcpMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpBuiltinRoute = SettingsMcpBuiltinRouteImport.update({
  id: '/builtin',
  path: '/builtin',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpSplatRoute = SettingsMcpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const AppPaintingsSplatRoute = AppPaintingsSplatRouteImport.update({
  id: '/paintings/$',
  path: '/paintings/$',
  getParentRoute: () => AppRoute,
} as any)
const AppMiniAppAppIdRoute = AppMiniAppAppIdRouteImport.update({
  id: '/mini-app/$appId',
  path: '/mini-app/$appId',
  getParentRoute: () => AppRoute,
} as any)
const SettingsMcpSettingsServerIdRoute =
  SettingsMcpSettingsServerIdRouteImport.update({
    id: '/settings/$serverId',
    path: '/settings/$serverId',
    getParentRoute: () => SettingsMcpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/chat': typeof AppChatRoute
  '/app/code': typeof AppCodeRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/launchpad': typeof AppLaunchpadRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/openclaw': typeof AppOpenclawRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-gateway': typeof SettingsApiGatewayRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/model': typeof SettingsModelRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quick-assistant': typeof SettingsQuickAssistantRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/selection-assistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/app/mini-app/$appId': typeof AppMiniAppAppIdRoute
  '/app/paintings/$': typeof AppPaintingsSplatRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/app/mini-app/': typeof AppMiniAppIndexRoute
  '/app/paintings/': typeof AppPaintingsIndexRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/chat': typeof AppChatRoute
  '/app/code': typeof AppCodeRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/launchpad': typeof AppLaunchpadRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/openclaw': typeof AppOpenclawRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-gateway': typeof SettingsApiGatewayRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quick-assistant': typeof SettingsQuickAssistantRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/selection-assistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings': typeof SettingsIndexRoute
  '/app/mini-app/$appId': typeof AppMiniAppAppIdRoute
  '/app/paintings/$': typeof AppPaintingsSplatRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/app/mini-app': typeof AppMiniAppIndexRoute
  '/app/paintings': typeof AppPaintingsIndexRoute
  '/settings/mcp': typeof SettingsMcpIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/chat': typeof AppChatRoute
  '/app/code': typeof AppCodeRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/launchpad': typeof AppLaunchpadRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/openclaw': typeof AppOpenclawRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-gateway': typeof SettingsApiGatewayRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/model': typeof SettingsModelRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quick-assistant': typeof SettingsQuickAssistantRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/selection-assistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/app/mini-app/$appId': typeof AppMiniAppAppIdRoute
  '/app/paintings/$': typeof AppPaintingsSplatRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/app/mini-app/': typeof AppMiniAppIndexRoute
  '/app/paintings/': typeof AppPaintingsIndexRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/settings'
    | '/app/agents'
    | '/app/chat'
    | '/app/code'
    | '/app/files'
    | '/app/knowledge'
    | '/app/launchpad'
    | '/app/library'
    | '/app/notes'
    | '/app/openclaw'
    | '/app/translate'
    | '/settings/about'
    | '/settings/api-gateway'
    | '/settings/channels'
    | '/settings/data'
    | '/settings/file-processing'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/plugins'
    | '/settings/provider'
    | '/settings/quick-assistant'
    | '/settings/scheduled-tasks'
    | '/settings/selection-assistant'
    | '/settings/shortcut'
    | '/settings/websearch'
    | '/settings/'
    | '/app/mini-app/$appId'
    | '/app/paintings/$'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/app/mini-app/'
    | '/app/paintings/'
    | '/settings/mcp/'
    | '/settings/mcp/settings/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/app/agents'
    | '/app/chat'
    | '/app/code'
    | '/app/files'
    | '/app/knowledge'
    | '/app/launchpad'
    | '/app/library'
    | '/app/notes'
    | '/app/openclaw'
    | '/app/translate'
    | '/settings/about'
    | '/settings/api-gateway'
    | '/settings/channels'
    | '/settings/data'
    | '/settings/file-processing'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/model'
    | '/settings/plugins'
    | '/settings/provider'
    | '/settings/quick-assistant'
    | '/settings/scheduled-tasks'
    | '/settings/selection-assistant'
    | '/settings/shortcut'
    | '/settings/websearch'
    | '/settings'
    | '/app/mini-app/$appId'
    | '/app/paintings/$'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/app/mini-app'
    | '/app/paintings'
    | '/settings/mcp'
    | '/settings/mcp/settings/$serverId'
  id:
    | '__root__'
    | '/app'
    | '/settings'
    | '/app/agents'
    | '/app/chat'
    | '/app/code'
    | '/app/files'
    | '/app/knowledge'
    | '/app/launchpad'
    | '/app/library'
    | '/app/notes'
    | '/app/openclaw'
    | '/app/translate'
    | '/settings/about'
    | '/settings/api-gateway'
    | '/settings/channels'
    | '/settings/data'
    | '/settings/file-processing'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/plugins'
    | '/settings/provider'
    | '/settings/quick-assistant'
    | '/settings/scheduled-tasks'
    | '/settings/selection-assistant'
    | '/settings/shortcut'
    | '/settings/websearch'
    | '/settings/'
    | '/app/mini-app/$appId'
    | '/app/paintings/$'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/app/mini-app/'
    | '/app/paintings/'
    | '/settings/mcp/'
    | '/settings/mcp/settings/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/websearch': {
      id: '/settings/websearch'
      path: '/websearch'
      fullPath: '/settings/websearch'
      preLoaderRoute: typeof SettingsWebsearchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shortcut': {
      id: '/settings/shortcut'
      path: '/shortcut'
      fullPath: '/settings/shortcut'
      preLoaderRoute: typeof SettingsShortcutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/selection-assistant': {
      id: '/settings/selection-assistant'
      path: '/selection-assistant'
      fullPath: '/settings/selection-assistant'
      preLoaderRoute: typeof SettingsSelectionAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scheduled-tasks': {
      id: '/settings/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/settings/scheduled-tasks'
      preLoaderRoute: typeof SettingsScheduledTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/quick-assistant': {
      id: '/settings/quick-assistant'
      path: '/quick-assistant'
      fullPath: '/settings/quick-assistant'
      preLoaderRoute: typeof SettingsQuickAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/plugins': {
      id: '/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/model': {
      id: '/settings/model'
      path: '/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof SettingsModelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/file-processing': {
      id: '/settings/file-processing'
      path: '/file-processing'
      fullPath: '/settings/file-processing'
      preLoaderRoute: typeof SettingsFileProcessingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/channels': {
      id: '/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof SettingsChannelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-gateway': {
      id: '/settings/api-gateway'
      path: '/api-gateway'
      fullPath: '/settings/api-gateway'
      preLoaderRoute: typeof SettingsApiGatewayRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/translate': {
      id: '/app/translate'
      path: '/translate'
      fullPath: '/app/translate'
      preLoaderRoute: typeof AppTranslateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/openclaw': {
      id: '/app/openclaw'
      path: '/openclaw'
      fullPath: '/app/openclaw'
      preLoaderRoute: typeof AppOpenclawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/launchpad': {
      id: '/app/launchpad'
      path: '/launchpad'
      fullPath: '/app/launchpad'
      preLoaderRoute: typeof AppLaunchpadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/code': {
      id: '/app/code'
      path: '/code'
      fullPath: '/app/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/mcp/': {
      id: '/settings/mcp/'
      path: '/'
      fullPath: '/settings/mcp/'
      preLoaderRoute: typeof SettingsMcpIndexRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/app/paintings/': {
      id: '/app/paintings/'
      path: '/paintings'
      fullPath: '/app/paintings/'
      preLoaderRoute: typeof AppPaintingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mini-app/': {
      id: '/app/mini-app/'
      path: '/mini-app'
      fullPath: '/app/mini-app/'
      preLoaderRoute: typeof AppMiniAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/mcp/servers': {
      id: '/settings/mcp/servers'
      path: '/servers'
      fullPath: '/settings/mcp/servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/npx-search': {
      id: '/settings/mcp/npx-search'
      path: '/npx-search'
      fullPath: '/settings/mcp/npx-search'
      preLoaderRoute: typeof SettingsMcpNpxSearchRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/mcp-install': {
      id: '/settings/mcp/mcp-install'
      path: '/mcp-install'
      fullPath: '/settings/mcp/mcp-install'
      preLoaderRoute: typeof SettingsMcpMcpInstallRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/marketplaces': {
      id: '/settings/mcp/marketplaces'
      path: '/marketplaces'
      fullPath: '/settings/mcp/marketplaces'
      preLoaderRoute: typeof SettingsMcpMarketplacesRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/builtin': {
      id: '/settings/mcp/builtin'
      path: '/builtin'
      fullPath: '/settings/mcp/builtin'
      preLoaderRoute: typeof SettingsMcpBuiltinRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/$': {
      id: '/settings/mcp/$'
      path: '/$'
      fullPath: '/settings/mcp/$'
      preLoaderRoute: typeof SettingsMcpSplatRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/app/paintings/$': {
      id: '/app/paintings/$'
      path: '/paintings/$'
      fullPath: '/app/paintings/$'
      preLoaderRoute: typeof AppPaintingsSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mini-app/$appId': {
      id: '/app/mini-app/$appId'
      path: '/mini-app/$appId'
      fullPath: '/app/mini-app/$appId'
      preLoaderRoute: typeof AppMiniAppAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/mcp/settings/$serverId': {
      id: '/settings/mcp/settings/$serverId'
      path: '/settings/$serverId'
      fullPath: '/settings/mcp/settings/$serverId'
      preLoaderRoute: typeof SettingsMcpSettingsServerIdRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppChatRoute: typeof AppChatRoute
  AppCodeRoute: typeof AppCodeRoute
  AppFilesRoute: typeof AppFilesRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLaunchpadRoute: typeof AppLaunchpadRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotesRoute: typeof AppNotesRoute
  AppOpenclawRoute: typeof AppOpenclawRoute
  AppTranslateRoute: typeof AppTranslateRoute
  AppMiniAppAppIdRoute: typeof AppMiniAppAppIdRoute
  AppPaintingsSplatRoute: typeof AppPaintingsSplatRoute
  AppMiniAppIndexRoute: typeof AppMiniAppIndexRoute
  AppPaintingsIndexRoute: typeof AppPaintingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppChatRoute: AppChatRoute,
  AppCodeRoute: AppCodeRoute,
  AppFilesRoute: AppFilesRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLaunchpadRoute: AppLaunchpadRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotesRoute: AppNotesRoute,
  AppOpenclawRoute: AppOpenclawRoute,
  AppTranslateRoute: AppTranslateRoute,
  AppMiniAppAppIdRoute: AppMiniAppAppIdRoute,
  AppPaintingsSplatRoute: AppPaintingsSplatRoute,
  AppMiniAppIndexRoute: AppMiniAppIndexRoute,
  AppPaintingsIndexRoute: AppPaintingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsMcpRouteChildren {
  SettingsMcpSplatRoute: typeof SettingsMcpSplatRoute
  SettingsMcpBuiltinRoute: typeof SettingsMcpBuiltinRoute
  SettingsMcpMarketplacesRoute: typeof SettingsMcpMarketplacesRoute
  SettingsMcpMcpInstallRoute: typeof SettingsMcpMcpInstallRoute
  SettingsMcpNpxSearchRoute: typeof SettingsMcpNpxSearchRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsMcpIndexRoute: typeof SettingsMcpIndexRoute
  SettingsMcpSettingsServerIdRoute: typeof SettingsMcpSettingsServerIdRoute
}

const SettingsMcpRouteChildren: SettingsMcpRouteChildren = {
  SettingsMcpSplatRoute: SettingsMcpSplatRoute,
  SettingsMcpBuiltinRoute: SettingsMcpBuiltinRoute,
  SettingsMcpMarketplacesRoute: SettingsMcpMarketplacesRoute,
  SettingsMcpMcpInstallRoute: SettingsMcpMcpInstallRoute,
  SettingsMcpNpxSearchRoute: SettingsMcpNpxSearchRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsMcpIndexRoute: SettingsMcpIndexRoute,
  SettingsMcpSettingsServerIdRoute: SettingsMcpSettingsServerIdRoute,
}

const SettingsMcpRouteWithChildren = SettingsMcpRoute._addFileChildren(
  SettingsMcpRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsApiGatewayRoute: typeof SettingsApiGatewayRoute
  SettingsChannelsRoute: typeof SettingsChannelsRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsFileProcessingRoute: typeof SettingsFileProcessingRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsMcpRoute: typeof SettingsMcpRouteWithChildren
  SettingsModelRoute: typeof SettingsModelRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsProviderRoute: typeof SettingsProviderRoute
  SettingsQuickAssistantRoute: typeof SettingsQuickAssistantRoute
  SettingsScheduledTasksRoute: typeof SettingsScheduledTasksRoute
  SettingsSelectionAssistantRoute: typeof SettingsSelectionAssistantRoute
  SettingsShortcutRoute: typeof SettingsShortcutRoute
  SettingsWebsearchRoute: typeof SettingsWebsearchRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsApiGatewayRoute: SettingsApiGatewayRoute,
  SettingsChannelsRoute: SettingsChannelsRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsFileProcessingRoute: SettingsFileProcessingRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsMcpRoute: SettingsMcpRouteWithChildren,
  SettingsModelRoute: SettingsModelRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsProviderRoute: SettingsProviderRoute,
  SettingsQuickAssistantRoute: SettingsQuickAssistantRoute,
  SettingsScheduledTasksRoute: SettingsScheduledTasksRoute,
  SettingsSelectionAssistantRoute: SettingsSelectionAssistantRoute,
  SettingsShortcutRoute: SettingsShortcutRoute,
  SettingsWebsearchRoute: SettingsWebsearchRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
